#!/bin/bash
# This script is used for submitting jobs to cluster.
# Job name: ThinfilmTank

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --cups-per-task=8

#SBATCH --mem-per-cpu=2012

#SBATCH --time=08:00:00

module load intel impi imkl

MY_NUM_THREADS=$SLURM_CPUS_PER_TASK

export OMP_NUM_THREADS=$MY_NUM_THREADS

srun lmp_mpi -in ThinFilmTank.MD
